#!/bin/bash

Rscript run_step_1.R -s AL -c 1000
Rscript run_step_1.R -s AR -c 1000 --local_entwine_index
Rscript run_step_1.R -s CT -c 1000 --local_entwine_index
Rscript run_step_1.R -s DC -c 1000 --local_entwine_index
Rscript run_step_1.R -s DE -c 1000 --local_entwine_index
Rscript run_step_1.R -s FL -c 1000 --local_entwine_index
Rscript run_step_1.R -s GA -c 1000 --local_entwine_index
Rscript run_step_1.R -s IA -c 1000 --local_entwine_index
Rscript run_step_1.R -s IL -c 1000 --local_entwine_index
Rscript run_step_1.R -s IN -c 1000 --local_entwine_index
Rscript run_step_1.R -s KY -c 1000 --local_entwine_index
Rscript run_step_1.R -s LA -c 1000 --local_entwine_index
Rscript run_step_1.R -s MA -c 1000 --local_entwine_index
Rscript run_step_1.R -s MD -c 1000 --local_entwine_index
Rscript run_step_1.R -s ME -c 1000 --local_entwine_index
Rscript run_step_1.R -s MI -c 1000 --local_entwine_index
Rscript run_step_1.R -s MN -c 1000 --local_entwine_index
Rscript run_step_1.R -s MO -c 1000 --local_entwine_index
Rscript run_step_1.R -s MS -c 1000 --local_entwine_index
Rscript run_step_1.R -s NC -c 1000 --local_entwine_index
Rscript run_step_1.R -s NH -c 1000 --local_entwine_index
Rscript run_step_1.R -s NJ -c 1000 --local_entwine_index
Rscript run_step_1.R -s NY -c 1000 --local_entwine_index
Rscript run_step_1.R -s OH -c 1000 --local_entwine_index
Rscript run_step_1.R -s PA -c 1000 --local_entwine_index
Rscript run_step_1.R -s PR -c 1000 --local_entwine_index
Rscript run_step_1.R -s RI -c 1000 --local_entwine_index
Rscript run_step_1.R -s SC -c 1000 --local_entwine_index
Rscript run_step_1.R -s TN -c 1000 --local_entwine_index
Rscript run_step_1.R -s VA -c 1000 --local_entwine_index
Rscript run_step_1.R -s VI -c 1000 --local_entwine_index
Rscript run_step_1.R -s VT -c 1000 --local_entwine_index
Rscript run_step_1.R -s WI -c 1000 --local_entwine_index
Rscript run_step_1.R -s WV -c 1000 --local_entwine_index
Rscript run_step_1.R -s AK -c 1000 --local_entwine_index
Rscript run_step_1.R -s AS -c 1000 --local_entwine_index
Rscript run_step_1.R -s AZ -c 1000 --local_entwine_index
Rscript run_step_1.R -s CA -c 1000 --local_entwine_index
Rscript run_step_1.R -s CO -c 1000 --local_entwine_index
Rscript run_step_1.R -s GU -c 1000 --local_entwine_index
Rscript run_step_1.R -s HI -c 1000 --local_entwine_index
Rscript run_step_1.R -s ID -c 1000 --local_entwine_index
Rscript run_step_1.R -s KS -c 1000 --local_entwine_index
Rscript run_step_1.R -s MP -c 1000 --local_entwine_index
Rscript run_step_1.R -s MT -c 1000 --local_entwine_index
Rscript run_step_1.R -s ND -c 1000 --local_entwine_index
Rscript run_step_1.R -s NE -c 1000 --local_entwine_index
Rscript run_step_1.R -s NM -c 1000 --local_entwine_index
Rscript run_step_1.R -s NV -c 1000 --local_entwine_index
Rscript run_step_1.R -s OK -c 1000 --local_entwine_index
Rscript run_step_1.R -s OR -c 1000 --local_entwine_index
Rscript run_step_1.R -s SD -c 1000 --local_entwine_index
Rscript run_step_1.R -s TX -c 1000 --local_entwine_index
Rscript run_step_1.R -s UT -c 1000 --local_entwine_index
Rscript run_step_1.R -s WA -c 1000 --local_entwine_index
Rscript run_step_1.R -s WY -c 1000 --local_entwine_index
