name: usgs_downloader
channels:
  - conda-forge
  - r
  - default
dependencies:
  - pdal=2.3
  - pip
  - python=3.9
  - r=3
  - r-devtools
  - r-ggplot2
  - r-lubridate
  - r-lwgeom
  - r-mapview
  - r-optparse
  - r-rmarkdown
  - r-rsqlite
  - r-tidyverse
  - r-udunits2

