name: usgs_downloader
channels:
  - conda-forge
  - r
  - default
dependencies:
  - pdal
  - pip
  - python
  - r=3
  - r-devtools
  - r-ggplot2
  - r-lubridate
  - r-lwgeom
  - r-mapview
  - r-rmarkdown
  - r-rsqlite
  - r-tidyverse
  - r-udunits2

